// handson-03-storybook-components/src/components/Modal/Modal.tsx
import React, { useEffect, useCallback } from 'react';
import clsx from 'clsx';

export interface ModalProps {
  /** モーダルの表示/非表示 */
  isOpen: boolean;
  /** 閉じる時のコールバック */
  onClose: () => void;
  /** モーダルタイトル */
  title?: string;
  /** モーダルサイズ */
  size?: 'sm' | 'md' | 'lg' | 'full';
  /** 確認ダイアログモード */
  confirmMode?: boolean;
  /** 確認ボタンテキスト */
  confirmText?: string;
  /** キャンセルボタンテキスト */
  cancelText?: string;
  /** 確認ボタン押下時のコールバック */
  onConfirm?: () => void;
  /** 確認ボタンのバリアント */
  confirmVariant?: 'primary' | 'danger';
  /** オーバーレイクリックで閉じるか */
  closeOnOverlay?: boolean;
  /** ESCキーで閉じるか */
  closeOnEsc?: boolean;
  /** フッター要素 */
  footer?: React.ReactNode;
  /** 子要素（ボディ） */
  children: React.ReactNode;
  /** 追加のCSSクラス */
  className?: string;
}

const sizeStyles: Record<string, string> = {
  sm: 'max-w-sm',
  md: 'max-w-lg',
  lg: 'max-w-3xl',
  full: 'max-w-full mx-4',
};

/**
 * Modal - モーダルダイアログコンポーネント
 *
 * 融資承認の確認、詳細情報の表示、
 * フォーム入力などに使用するモーダルです。
 * 確認ダイアログモードでは承認/却下の確認に最適です。
 */
export const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title,
  size = 'md',
  confirmMode = false,
  confirmText = '確認',
  cancelText = 'キャンセル',
  onConfirm,
  confirmVariant = 'primary',
  closeOnOverlay = true,
  closeOnEsc = true,
  footer,
  children,
  className,
}) => {
  const handleEsc = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === 'Escape' && closeOnEsc) onClose();
    },
    [onClose, closeOnEsc]
  );

  useEffect(() => {
    if (isOpen) {
      document.addEventListener('keydown', handleEsc);
      document.body.style.overflow = 'hidden';
    }
    return () => {
      document.removeEventListener('keydown', handleEsc);
      document.body.style.overflow = '';
    };
  }, [isOpen, handleEsc]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Overlay */}
      <div
        className="absolute inset-0 bg-black/50 transition-opacity"
        onClick={closeOnOverlay ? onClose : undefined}
      />

      {/* Modal */}
      <div
        className={clsx(
          'relative w-full bg-white rounded-lg shadow-xl',
          sizeStyles[size],
          className
        )}
      >
        {/* Header */}
        {title && (
          <div className="flex items-center justify-between px-6 py-4 border-b border-fin-border">
            <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
            <button
              onClick={onClose}
              className="p-1 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        )}

        {/* Body */}
        <div className="px-6 py-4">{children}</div>

        {/* Footer */}
        {(confirmMode || footer) && (
          <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-fin-border bg-gray-50 rounded-b-lg">
            {confirmMode ? (
              <>
                <button
                  onClick={onClose}
                  className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-fin-border rounded-md hover:bg-gray-50"
                >
                  {cancelText}
                </button>
                <button
                  onClick={onConfirm}
                  className={clsx(
                    'px-4 py-2 text-sm font-medium text-white rounded-md',
                    confirmVariant === 'danger'
                      ? 'bg-fin-danger hover:bg-fin-danger-hover'
                      : 'bg-fin-primary hover:bg-fin-primary-hover'
                  )}
                >
                  {confirmText}
                </button>
              </>
            ) : (
              footer
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default Modal;

// handson-03-storybook-components/src/components/Modal/modal.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface ModalProps {
  isOpen: boolean;
  title?: string;
  size?: 'sm' | 'md' | 'lg' | 'full';
  confirmMode?: boolean;
  confirmText?: string;
  cancelText?: string;
  confirmVariant?: 'primary' | 'danger';
  closeOnOverlay?: boolean;
  closeOnEsc?: boolean;
}

const sizeStyles: Record<string, string> = {
  sm: 'max-w-sm',
  md: 'max-w-lg',
  lg: 'max-w-3xl',
  full: 'max-w-full mx-4',
};

/**
 * Modal - モーダルダイアログコンポーネント
 *
 * 融資承認の確認、詳細情報の表示、
 * フォーム入力などに使用するモーダルです。
 */
@Component({
  selector: 'fin-modal',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './modal.component.html',
})
export class ModalComponent implements OnInit, OnDestroy {
  @Input() isOpen = false;
  @Input() title?: string;
  @Input() size: 'sm' | 'md' | 'lg' | 'full' = 'md';
  @Input() confirmMode = false;
  @Input() confirmText = '確認';
  @Input() cancelText = 'キャンセル';
  @Input() confirmVariant: 'primary' | 'danger' = 'primary';
  @Input() closeOnOverlay = true;
  @Input() closeOnEsc = true;
  @Input() className = '';

  @Output() modalClose = new EventEmitter<void>();
  @Output() confirm = new EventEmitter<void>();

  private escHandler = (e: KeyboardEvent) => {
    if (e.key === 'Escape' && this.closeOnEsc && this.isOpen) {
      this.modalClose.emit();
    }
  };

  ngOnInit(): void {
    document.addEventListener('keydown', this.escHandler);
  }

  ngOnDestroy(): void {
    document.removeEventListener('keydown', this.escHandler);
    document.body.style.overflow = '';
  }

  get modalClasses(): string {
    const classes = ['relative w-full bg-white rounded-lg shadow-xl', sizeStyles[this.size]];
    if (this.className) classes.push(this.className);
    return classes.join(' ');
  }

  get confirmButtonClasses(): string {
    return this.confirmVariant === 'danger'
      ? 'px-4 py-2 text-sm font-medium text-white rounded-md bg-fin-danger hover:bg-fin-danger-hover'
      : 'px-4 py-2 text-sm font-medium text-white rounded-md bg-fin-primary hover:bg-fin-primary-hover';
  }

  onOverlayClick(): void {
    if (this.closeOnOverlay) this.modalClose.emit();
  }

  onConfirm(): void {
    this.confirm.emit();
  }

  onClose(): void {
    this.modalClose.emit();
  }
}

@if (isOpen) {
  <div class="fixed inset-0 z-50 flex items-center justify-center">
    <!-- Overlay -->
    <div
      class="absolute inset-0 bg-black/50 transition-opacity"
      (click)="onOverlayClick()"
    ></div>

    <!-- Modal -->
    <div [class]="modalClasses">
      <!-- Header -->
      @if (title) {
        <div class="flex items-center justify-between px-6 py-4 border-b border-fin-border">
          <h3 class="text-lg font-semibold text-gray-900">{{ title }}</h3>
          <button
            (click)="onClose()"
            class="p-1 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100"
          >
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      }

      <!-- Body -->
      <div class="px-6 py-4">
        <ng-content></ng-content>
      </div>

      <!-- Footer -->
      @if (confirmMode) {
        <div class="flex items-center justify-end gap-3 px-6 py-4 border-t border-fin-border bg-gray-50 rounded-b-lg">
          <button
            (click)="onClose()"
            class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-fin-border rounded-md hover:bg-gray-50"
          >
            {{ cancelText }}
          </button>
          <button
            (click)="onConfirm()"
            [class]="confirmButtonClasses"
          >
            {{ confirmText }}
          </button>
        </div>
      }
      <ng-content select="[footer]"></ng-content>
    </div>
  </div>
}
