// handson-03-storybook-components/src/components/LineChart/line-chart.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BaseChartDirective } from 'ng2-charts';
import { ChartConfiguration, ChartData } from 'chart.js';

export interface LineChartSeries {
  /** データキー */
  dataKey: string;
  /** 系列名 */
  name: string;
  /** 線の色 */
  color?: string;
  /** 破線パターン */
  strokeDasharray?: string;
}

export interface LineChartProps {
  data: Record<string, unknown>[];
  xAxisKey: string;
  series: LineChartSeries[];
  height?: number;
  showGrid?: boolean;
  showLegend?: boolean;
}

const defaultColors = ['#1E40AF', '#DC2626', '#16A34A', '#D97706', '#7C3AED', '#0891B2'];

/**
 * 日本円フォーマット
 */
const formatJPY = (value: number): string => {
  if (value >= 100000000) return `${(value / 100000000).toFixed(1)}億円`;
  if (value >= 10000) return `${(value / 10000).toFixed(0)}万円`;
  return `¥${value.toLocaleString()}`;
};

/**
 * LineChart - 折れ線グラフコンポーネント
 *
 * 融資残高推移、月次申請件数推移、延滞率推移など、
 * 時系列データの可視化に使用します。
 * Chart.js + ng2-chartsベースでレスポンシブ対応です。
 */
@Component({
  selector: 'fin-line-chart',
  standalone: true,
  imports: [CommonModule, BaseChartDirective],
  templateUrl: './line-chart.component.html',
})
export class LineChartComponent implements OnChanges {
  @Input() data: Record<string, unknown>[] = [];
  @Input() xAxisKey = '';
  @Input() series: LineChartSeries[] = [];
  @Input() height = 300;
  @Input() yAxisFormatter: ((value: number) => string) | null = null;
  @Input() tooltipFormatter: ((value: number) => string) | null = null;
  @Input() showGrid = true;
  @Input() showLegend = true;
  @Input() className = '';

  chartData: ChartData<'line'> = { labels: [], datasets: [] };
  chartOptions: ChartConfiguration<'line'>['options'] = {};

  private getFormatter(): (value: number) => string {
    return this.yAxisFormatter || formatJPY;
  }

  private getTooltipFormatter(): (value: number) => string {
    return this.tooltipFormatter || formatJPY;
  }

  ngOnChanges(_changes: SimpleChanges): void {
    this.updateChart();
  }

  private updateChart(): void {
    const labels = this.data.map((d) => String(d[this.xAxisKey] ?? ''));
    const datasets = this.series.map((s, i) => {
      const color = s.color || defaultColors[i % defaultColors.length];
      const borderDash = s.strokeDasharray ? s.strokeDasharray.split(' ').map(Number) : [];
      return {
        label: s.name,
        data: this.data.map((d) => Number(d[s.dataKey] ?? 0)),
        borderColor: color,
        backgroundColor: color,
        borderWidth: 2,
        borderDash,
        pointRadius: 3,
        pointHoverRadius: 5,
        tension: 0.3,
        fill: false,
      };
    });

    this.chartData = { labels, datasets };

    const formatter = this.getFormatter();
    const tipFormatter = this.getTooltipFormatter();

    this.chartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          display: this.showLegend,
        },
        tooltip: {
          callbacks: {
            label: (context) => {
              const label = context.dataset.label || '';
              const value = context.parsed.y;
              return `${label}: ${tipFormatter(value)}`;
            },
          },
        },
      },
      scales: {
        x: {
          grid: { display: this.showGrid, color: '#E2E8F0' },
          ticks: { font: { size: 12 }, color: '#64748B' },
          border: { color: '#E2E8F0' },
        },
        y: {
          grid: { display: this.showGrid, color: '#E2E8F0' },
          ticks: {
            font: { size: 12 },
            color: '#64748B',
            callback: (value) => formatter(Number(value)),
          },
          border: { color: '#E2E8F0' },
        },
      },
    };
  }
}

<div [class]="className" [style.height.px]="height">
  <canvas
    baseChart
    type="line"
    [data]="chartData"
    [options]="chartOptions"
  ></canvas>
</div>

// handson-03-storybook-components/src/components/LineChart/LineChart.tsx
import React from 'react';
import {
  LineChart as RechartsLineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';

export interface LineChartSeries {
  /** データキー */
  dataKey: string;
  /** 系列名 */
  name: string;
  /** 線の色 */
  color?: string;
  /** 破線パターン */
  strokeDasharray?: string;
}

export interface LineChartProps {
  /** チャートデータ */
  data: Record<string, unknown>[];
  /** X軸のデータキー */
  xAxisKey: string;
  /** 系列定義 */
  series: LineChartSeries[];
  /** チャートの高さ */
  height?: number;
  /** Y軸のフォーマッター */
  yAxisFormatter?: (value: number) => string;
  /** ツールチップのフォーマッター */
  tooltipFormatter?: (value: number) => string;
  /** グリッド表示 */
  showGrid?: boolean;
  /** 凡例表示 */
  showLegend?: boolean;
  /** 追加のCSSクラス */
  className?: string;
}

const defaultColors = ['#1E40AF', '#DC2626', '#16A34A', '#D97706', '#7C3AED', '#0891B2'];

/**
 * 日本円フォーマット
 */
const formatJPY = (value: number): string => {
  if (value >= 100000000) return `${(value / 100000000).toFixed(1)}億円`;
  if (value >= 10000) return `${(value / 10000).toFixed(0)}万円`;
  return `¥${value.toLocaleString()}`;
};

/**
 * LineChart - 折れ線グラフコンポーネント
 *
 * 融資残高推移、月次申請件数推移、延滞率推移など、
 * 時系列データの可視化に使用します。
 * Rechartsベースでレスポンシブ対応です。
 */
export const LineChart: React.FC<LineChartProps> = ({
  data,
  xAxisKey,
  series,
  height = 300,
  yAxisFormatter = formatJPY,
  tooltipFormatter = formatJPY,
  showGrid = true,
  showLegend = true,
  className,
}) => {
  return (
    <div className={className}>
      <ResponsiveContainer width="100%" height={height}>
        <RechartsLineChart data={data} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
          {showGrid && <CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" />}
          <XAxis
            dataKey={xAxisKey}
            tick={{ fontSize: 12, fill: '#64748B' }}
            tickLine={false}
            axisLine={{ stroke: '#E2E8F0' }}
          />
          <YAxis
            tickFormatter={yAxisFormatter}
            tick={{ fontSize: 12, fill: '#64748B' }}
            tickLine={false}
            axisLine={{ stroke: '#E2E8F0' }}
          />
          <Tooltip
            formatter={(value: number, name: string) => [tooltipFormatter(value), name]}
            contentStyle={{
              borderRadius: '8px',
              border: '1px solid #E2E8F0',
              boxShadow: '0 4px 6px -1px rgba(0,0,0,0.1)',
            }}
          />
          {showLegend && <Legend />}
          {series.map((s, i) => (
            <Line
              key={s.dataKey}
              type="monotone"
              dataKey={s.dataKey}
              name={s.name}
              stroke={s.color || defaultColors[i % defaultColors.length]}
              strokeWidth={2}
              strokeDasharray={s.strokeDasharray}
              dot={{ r: 3 }}
              activeDot={{ r: 5 }}
            />
          ))}
        </RechartsLineChart>
      </ResponsiveContainer>
    </div>
  );
};

export default LineChart;
