// handson-03-storybook-components/src/components/Sidebar/Sidebar.tsx
import React, { useState } from 'react';
import clsx from 'clsx';

export interface SidebarSubItem {
  /** キー */
  key: string;
  /** ラベル */
  label: string;
  /** リンク先 */
  href?: string;
}

export interface SidebarItem {
  /** キー */
  key: string;
  /** ラベル */
  label: string;
  /** アイコン */
  icon: React.ReactNode;
  /** リンク先 */
  href?: string;
  /** サブメニュー */
  children?: SidebarSubItem[];
  /** バッジ */
  badge?: number;
}

export interface SidebarProps {
  /** メニュー項目 */
  items: SidebarItem[];
  /** アクティブなメニューキー */
  activeKey?: string;
  /** メニュークリック時のコールバック */
  onItemClick?: (key: string) => void;
  /** 折りたたみ状態 */
  collapsed?: boolean;
  /** 折りたたみ切替コールバック */
  onCollapsedChange?: (collapsed: boolean) => void;
  /** ヘッダー要素 */
  header?: React.ReactNode;
  /** 追加のCSSクラス */
  className?: string;
}

/**
 * Sidebar - サイドバーナビゲーションコンポーネント
 *
 * 金融システムのメイン画面ナビゲーションとして使用します。
 * 折りたたみ対応で、サブメニューも表示できます。
 */
export const Sidebar: React.FC<SidebarProps> = ({
  items,
  activeKey,
  onItemClick,
  collapsed = false,
  onCollapsedChange,
  header,
  className,
}) => {
  const [expandedKeys, setExpandedKeys] = useState<string[]>([]);

  const toggleExpand = (key: string) => {
    setExpandedKeys((prev) =>
      prev.includes(key) ? prev.filter((k) => k !== key) : [...prev, key]
    );
  };

  return (
    <aside
      className={clsx(
        'flex flex-col bg-gray-900 text-white transition-all duration-300',
        collapsed ? 'w-16' : 'w-64',
        className
      )}
    >
      {/* ヘッダー */}
      <div className="flex items-center justify-between px-4 py-4 border-b border-gray-700">
        {!collapsed && (header || <span className="text-lg font-bold">FinUI</span>)}
        <button
          onClick={() => onCollapsedChange?.(!collapsed)}
          className="p-1 rounded hover:bg-gray-700"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d={collapsed ? 'M13 5l7 7-7 7M5 5l7 7-7 7' : 'M11 19l-7-7 7-7M19 19l-7-7 7-7'}
            />
          </svg>
        </button>
      </div>

      {/* メニュー */}
      <nav className="flex-1 py-4 overflow-y-auto">
        {items.map((item) => {
          const isActive = activeKey === item.key;
          const isExpanded = expandedKeys.includes(item.key);
          const hasChildren = item.children && item.children.length > 0;

          return (
            <div key={item.key}>
              <button
                onClick={() => {
                  if (hasChildren && !collapsed) {
                    toggleExpand(item.key);
                  }
                  onItemClick?.(item.key);
                }}
                className={clsx(
                  'w-full flex items-center gap-3 px-4 py-2.5 text-sm transition-colors',
                  isActive
                    ? 'bg-fin-primary text-white'
                    : 'text-gray-300 hover:bg-gray-800 hover:text-white',
                  collapsed && 'justify-center'
                )}
                title={collapsed ? item.label : undefined}
              >
                <span className="flex-shrink-0">{item.icon}</span>
                {!collapsed && (
                  <>
                    <span className="flex-1 text-left">{item.label}</span>
                    {item.badge != null && (
                      <span className="px-2 py-0.5 text-xs bg-fin-danger rounded-full">
                        {item.badge}
                      </span>
                    )}
                    {hasChildren && (
                      <svg
                        className={clsx('w-4 h-4 transition-transform', isExpanded && 'rotate-90')}
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    )}
                  </>
                )}
              </button>

              {/* サブメニュー */}
              {hasChildren && isExpanded && !collapsed && (
                <div className="bg-gray-950">
                  {item.children!.map((child) => (
                    <button
                      key={child.key}
                      onClick={() => onItemClick?.(child.key)}
                      className={clsx(
                        'w-full text-left pl-12 pr-4 py-2 text-sm transition-colors',
                        activeKey === child.key
                          ? 'text-white bg-gray-800'
                          : 'text-gray-400 hover:text-white hover:bg-gray-800'
                      )}
                    >
                      {child.label}
                    </button>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </nav>
    </aside>
  );
};

export default Sidebar;

// handson-03-storybook-components/src/components/Sidebar/sidebar.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface SidebarSubItem {
  key: string;
  label: string;
  href?: string;
}

export interface SidebarItem {
  key: string;
  label: string;
  iconPath: string;
  href?: string;
  children?: SidebarSubItem[];
  badge?: number;
}

export interface SidebarProps {
  items: SidebarItem[];
  activeKey?: string;
  collapsed?: boolean;
}

/**
 * Sidebar - サイドバーナビゲーションコンポーネント
 *
 * 金融システムのメイン画面ナビゲーションとして使用します。
 * 折りたたみ対応で、サブメニューも表示できます。
 */
@Component({
  selector: 'fin-sidebar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './sidebar.component.html',
})
export class SidebarComponent {
  @Input() items: SidebarItem[] = [];
  @Input() activeKey?: string;
  @Input() collapsed = false;
  @Input() className = '';

  @Output() itemClick = new EventEmitter<string>();
  @Output() collapsedChange = new EventEmitter<boolean>();

  expandedKeys: string[] = [];

  get sidebarClasses(): string {
    const classes = [
      'flex flex-col bg-gray-900 text-white transition-all duration-300',
      this.collapsed ? 'w-16' : 'w-64',
    ];
    if (this.className) classes.push(this.className);
    return classes.join(' ');
  }

  get collapseIconPath(): string {
    return this.collapsed
      ? 'M13 5l7 7-7 7M5 5l7 7-7 7'
      : 'M11 19l-7-7 7-7M19 19l-7-7 7-7';
  }

  toggleCollapse(): void {
    this.collapsedChange.emit(!this.collapsed);
  }

  toggleExpand(key: string): void {
    if (this.expandedKeys.includes(key)) {
      this.expandedKeys = this.expandedKeys.filter((k) => k !== key);
    } else {
      this.expandedKeys = [...this.expandedKeys, key];
    }
  }

  isExpanded(key: string): boolean {
    return this.expandedKeys.includes(key);
  }

  hasChildren(item: SidebarItem): boolean {
    return !!item.children && item.children.length > 0;
  }

  onItemClick(item: SidebarItem): void {
    if (this.hasChildren(item) && !this.collapsed) {
      this.toggleExpand(item.key);
    }
    this.itemClick.emit(item.key);
  }

  onSubItemClick(key: string): void {
    this.itemClick.emit(key);
  }

  getItemClasses(item: SidebarItem): string {
    const classes = [
      'w-full flex items-center gap-3 px-4 py-2.5 text-sm transition-colors',
    ];
    if (this.activeKey === item.key) {
      classes.push('bg-fin-primary text-white');
    } else {
      classes.push('text-gray-300 hover:bg-gray-800 hover:text-white');
    }
    if (this.collapsed) classes.push('justify-center');
    return classes.join(' ');
  }

  getSubItemClasses(key: string): string {
    const classes = [
      'w-full text-left pl-12 pr-4 py-2 text-sm transition-colors',
    ];
    if (this.activeKey === key) {
      classes.push('text-white bg-gray-800');
    } else {
      classes.push('text-gray-400 hover:text-white hover:bg-gray-800');
    }
    return classes.join(' ');
  }
}

<aside [class]="sidebarClasses">
  <!-- ヘッダー -->
  <div class="flex items-center justify-between px-4 py-4 border-b border-gray-700">
    @if (!collapsed) {
      <ng-content select="[header]"></ng-content>
      @if (!collapsed) {
        <span class="text-lg font-bold">FinUI</span>
      }
    }
    <button (click)="toggleCollapse()" class="p-1 rounded hover:bg-gray-700">
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" [attr.d]="collapseIconPath" />
      </svg>
    </button>
  </div>

  <!-- メニュー -->
  <nav class="flex-1 py-4 overflow-y-auto">
    @for (item of items; track item.key) {
      <div>
        <button
          [class]="getItemClasses(item)"
          [title]="collapsed ? item.label : ''"
          (click)="onItemClick(item)"
        >
          <span class="flex-shrink-0">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" [attr.d]="item.iconPath" />
            </svg>
          </span>
          @if (!collapsed) {
            <span class="flex-1 text-left">{{ item.label }}</span>
            @if (item.badge != null) {
              <span class="px-2 py-0.5 text-xs bg-fin-danger rounded-full">{{ item.badge }}</span>
            }
            @if (hasChildren(item)) {
              <svg
                class="w-4 h-4 transition-transform"
                [class.rotate-90]="isExpanded(item.key)"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
              </svg>
            }
          }
        </button>

        <!-- サブメニュー -->
        @if (hasChildren(item) && isExpanded(item.key) && !collapsed) {
          <div class="bg-gray-950">
            @for (child of item.children; track child.key) {
              <button
                [class]="getSubItemClasses(child.key)"
                (click)="onSubItemClick(child.key)"
              >
                {{ child.label }}
              </button>
            }
          </div>
        }
      </div>
    }
  </nav>
</aside>
